### ISSUE TITLE
Memory leak in xstatbar.c:draw()

### ISSUE THREAD

**Issue by farhaven** [ryanflannery/xstatbar#6]
The call to `XCopyArea` in `draw()` generates one of two X events, either a `GraphicsExpose` or a `NoExpose` event. Since `xstatbar` does not have one of those traditional X event loops, those events accumulate in the event queue and lead to a memory leak. The easiest fix is to call `XNextEvent` after `XCopyArea` to consume the events it generated. 

The following patch addresses the issue:
```
--- xstatbar.c.orig	Tue Feb  9 11:18:02 2016
+++ xstatbar.c	Tue Feb  9 11:19:05 2016
@@ -297,6 +297,7 @@
 void
 draw()
 {
+   XEvent dummy;
    static int spacing = 10;
    int x, y;
    int cpu;
@@ -323,6 +324,7 @@
    /* copy the buffer to the window and flush */
    XCopyArea(XINFO.disp, XINFO.buf, XINFO.win, XINFO.gc,
       0, 0, XINFO.width, XINFO.height, 0, 0);
+   XNextEvent(XINFO.disp, &dummy);
    XFlush(XINFO.disp);
 }
 ```

**Comment by ryanflannery** [comment]
Looks good. Thanks!

**Comment by ryanflannery** [comment]
Pushed patch in 8aa437dc059b2161c43811344da903f4ca57d7e0
